version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-homepage
    ports:
      - "3001:80"
    restart: unless-stopped
    # For development with hot-reload, uncomment these lines:
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
    environment:
      - NODE_ENV=production
      # Add any other environment variables your app needs

# If you need persistence or other services like a database, add them here 